#development:
#  adapter: sqlite3
#  database: db/developmnet.sqlite3
#  pool: 5
#
#production:
#   adapter: sqlite3
#   database: db/developmnet.sqlite3
#   pool: 5
#
#test:
#    adapter: sqlite3
#    database: db/developmnet.sqlite3
#    pool: 5
  development:
    encoding: unicode
    adapter: postgresql
    username: postgres
    database: rds_development
    password: password
    min_messages: warning

  test:
    encoding: unicode
    adapter: postgresql
    username: postgres
    database: rds_test
    password:
    min_messages: warning